# Generated by Django 4.1.7 on 2023-03-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ratting',
            new_name='mrating',
        ),
    ]
